chore: release v4.6.0
dequelabs/axe-core-gems pull request #288
Opened 2023-01-19 18:32 UTC by AdnoC

2023-01-19 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core-gems?pullRequest=288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core-gems?pullRequest=288) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: stephenmathieson<br/>:white_check_mark: michael-siek<br/>:white_check_mark: AdnoC<br/>:x: attest-team-ci<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core-gems?pullRequest=288) it.</sub>

2023-01-19 22:08 UTC, straker requested changes
I think https://github.com/dequelabs/axe-core-gems/pull/286 needs to be part of the release. It adds a change to the core files that are needed to use the new selectors

2023-01-24 21:49 UTC, straker approved these changes

2023-01-26 00:12 UTC, michael-siek commented
# Release Audit v4.6.0
- [x] https://github.com/dequelabs/axe-core-gems/pull/283
- [x] https://github.com/dequelabs/axe-core-gems/pull/278
- [x] https://github.com/dequelabs/axe-core-gems/pull/285

2023-01-26 00:13 UTC, merged

2023-01-27 15:07 UTC, dylanb commented
reviewed