fix: gracefully handle unloaded iframes
dequelabs/axe-core-gems pull request #315
Opened 2023-07-17 13:09 UTC by AdnoC

https://github.com/dequelabs/axe-core-gems/issues/313

2023-07-17 15:58 UTC, stephenmathieson requested changes

2023-07-17 15:58 UTC, stephenmathieson commented on packages/axe-core-api/lib/axe/core.rb
> +      # raise Exception.new "Page/frame not ready" if not ready
```suggestion
      end
```

2023-08-22 15:49 UTC, straker requested changes
Also [missing the test](https://github.com/dequelabs/axe-core-npm/pull/743/files#diff-df471be74b5a7833eef1a1ad0202032f0d9535daee3832c0f922694dacdd6eafR421-R432) that verifies we reset page load timeout to user setting

2023-08-22 15:49 UTC, straker commented on packages/axe-core-api/lib/axe/api/run.rb
> +        (get_selenium page).manage.timeouts.page_load = 1
Need to unset this after runPartial

2023-08-23 16:09 UTC, straker approved these changes

2023-08-24 15:51 UTC, merged